apiVersion: v1
data:
  license-key: <GLOO_EDGE_LICENSE_KEY> # insert base64 encoded license key here
kind: Secret
metadata:
  labels:
    app: gloo
    app.kubernetes.io/instance: gloo-edge-enterprise-helm
    gloo: license
  name: license
  namespace: gloo-system
type: Opaque